/* ANALÍTICO DE CORTE — MÊS (POR PEDIDO/PRODUTO) — PARAM :DATAI, :DATAF */
SELECT TO_CHAR(PCCORTEI.DATA, 'DD/MM/YYYY')                  AS DATA,
       PCCORTEI.CODFILIAL                                    AS CODFILIAL,
       PCCORTEI.NUMPED                                       AS NUMPED,
       PCPEDC.POSICAO,
       UPPER(PCPEDC.CODSUPERVISOR || ' - ' || PCSUPERV.NOME) AS SUPERVISAO,
       PCPEDC.CODUSUR || ' - ' || PCUSUARI.NOME              AS RCA,
       PCPRODUT.CODPROD                                      AS CODPROD,
       PCPRODUT.DESCRICAO                                    AS DESCRICAO,
       PCCORTEI.QTCORTADA                                    AS QT_CORTE,
       ROUND(PCCORTEI.QTCORTADA * PCCORTEI.PVENDA, 2)        AS PVENDA_CORTE
FROM PCPRODUT
         JOIN PCEST ON PCEST.CODPROD = PCPRODUT.CODPROD
         JOIN PCCORTEI ON PCCORTEI.CODPROD = PCPRODUT.CODPROD
    AND PCCORTEI.CODFILIAL = PCEST.CODFILIAL
         LEFT JOIN PCPEDC ON PCPEDC.NUMPED = PCCORTEI.NUMPED
    AND PCPEDC.CODFILIAL = PCCORTEI.CODFILIAL
         LEFT JOIN PCSUPERV ON PCSUPERV.CODSUPERVISOR = PCPEDC.CODSUPERVISOR
         LEFT JOIN PCUSUARI ON PCUSUARI.CODUSUR = PCPEDC.CODUSUR
WHERE PCCORTEI.NUMPED IS NOT NULL
  AND PCCORTEI.DATA BETWEEN :DATAI AND :DATAF
ORDER BY PCCORTEI.DATA DESC,
         PCCORTEI.CODFILIAL,
         (PCCORTEI.QTCORTADA * PCCORTEI.PVENDA) DESC,
         PCPRODUT.DESCRICAO